### ISSUE TITLE
zsh: command not found: ros2

### ISSUE THREAD

**Issue by Ninagawa123** [TakanoTaiga/ros2_m1_native#3]
Thanks for the great guidance.
I followed the instructions and installed under the documents folder.
The installation itself seems to be working, but I am unable to run the ros2 command.
The same result was obtained when I launched a new window.
I suspect the paths are not set correctly, but please let me know if there is anything additional that needs to be written to the .zshrc.

**Comment by takanotaiga** [comment]
I apologize for the delayed response. I have added it to the Qiita article mentioned in the README.
